name: build
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      # - name: docker build
      #   run : | 
      #     docker build -t crawl:latest .
      - name: build
        run : |
          docker buildx build -t crawl:latest --platform linux/i386,linux/x86_64 .
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

